repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Find the latest version on the ruff-pre-commit repository
    rev: v0.12.8 
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix] # Optional: automatically fix what it can
      # Run the formatter
      - id: ruff-format